global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kafka-consumer'
    static_configs:
      - targets: ['clickstream-analytics-consumer-1:8000']  # Use service name when running with Docker